services:
  - type: web
    name: soc-threat-analysis
    env: python
    buildCommand: pip install -r requirements.txt && python train_models.py
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
